# Generated by Django 4.2.7 on 2023-11-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createteam',
            name='teamcaptain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
