# Generated by Django 4.2.7 on 2023-11-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='team',
        ),
        migrations.AddField(
            model_name='notification',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
    ]
