# Generated by Django 4.2.7 on 2023-12-16 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gullyapp', '0006_remove_notification_team_id_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createteam',
            name='teamcaptain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
