# Generated by Django 4.2.7 on 2023-12-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0008_remove_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createteam',
            name='current_location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
