# Generated by Django 4.2.7 on 2023-12-16 08:06

from django.db import migrations, models

from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0009_createteam_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
