# Generated by Django 4.2.7 on 2023-12-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0010_notification_is_accepted_notification_is_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
