# Generated by Django 4.2.7 on 2023-12-17 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0012_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createteam',
            name='current_location',
        ),
    ]
