# Generated by Django 4.2.7 on 2023-12-17 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0013_remove_createteam_current_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShownTeamsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shown_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shown_teams', to='gullyapp.createteam')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gullyapp.createteam')),
            ],
        ),
    ]
