# Generated by Django 4.2.7 on 2023-12-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gullyapp', '0016_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='challenge_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
